## Table of Contents
- [Introduction to Tensors](#introduction-to-tensors)
  - [Creating Tensors](#creating-tensors)
  - [Random Tensors](#random-tensors)
  - [Zeros and Ones](#zeros-and-ones)
  - [Creating a range and tensors like](#creating-a-range-and-tensors-like)
  - [Tensor datatypes](#tensor-datatypes)
  - [Getting information from tensors](#getting-information-from-tensors)
  - [Manipulating Tensors (Tensor Operations)](#manipulating-tensors-tensor-operations)
  - [One of the most common errors in deep learning (shape errors)](#one-of-the-most-common-errors-in-deep-learning-shape-errors)
- [Finding the min, max, mean, sum, etc (aggregation)](#finding-the-min-max-mean-sum-etc-aggregation)
- [Positional min/max](#positional-minmax)
- [Change tensor datatype](#change-tensor-datatype)
- [Reshaping, stacking, squeezing and unsqueezing tensors](#reshaping-stacking-squeezing-and-unsqueezing-tensors)
- [Indexing (selecting data from tensors)](#indexing-selecting-data-from-tensors)
- [PyTorch tensors & NumPy](#pytorch-tensors--numpy)
- [Reproducibility (trying to take the random out of random)](#reproducibility-trying-to-take-the-random-out-of-random)
- [Running tensors and PyTorch objects on the GPUs](#running-tensors-and-pytorch-objects-on-the-gpus)


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors
### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Puython int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[0][1]

tensor(8)

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[ 4, 7, 2],
                        [ 9, 1, 5],
                        [ 3, 2, 8]],
                       [[3, 6, 2],
                        [9, 8, 4],
                        [4, 2, 6]],
                       [[8, 3, 3],
                        [9, 7, 5],
                        [8, 4, 7]]])

In [14]:
TENSOR

tensor([[[4, 7, 2],
         [9, 1, 5],
         [3, 2, 8]],

        [[3, 6, 2],
         [9, 8, 4],
         [4, 2, 6]],

        [[8, 3, 3],
         [9, 7, 5],
         [8, 4, 7]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([3, 3, 3])

In [17]:
TENSOR[0]

tensor([[4, 7, 2],
        [9, 1, 5],
        [3, 2, 8]])

### Random Tensors
<div style="font-size: 15px;">


Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

</div>

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))

In [19]:
random_tensor, random_tensor.dtype

(tensor([[0.4221, 0.4945, 0.5487, 0.1407],
         [0.2251, 0.9748, 0.0497, 0.7268],
         [0.2735, 0.8496, 0.7421, 0.0022]]),
 torch.float32)

In [20]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones


In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [23]:
# Use torch.arange(), torch.range() is deprecated 
# zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 1 to 10
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_ones = torch.ones_like(input = one_to_ten)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

### Tensor datatypes

In [25]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True operations performed on the tensor are recorded 

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

<div style="font-size: 15px;">

**Note:** 3 most common attributes of a tensor:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

</div>

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16) # Changing the data type
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32) # Declaring the data type
int_32_tensor, int_32_tensor * float_32_tensor

(tensor([3, 6, 9], dtype=torch.int32), tensor([ 9., 36., 81.]))

<div style="font-size: 15px;">

### Getting information from tensors
1. To get datatype from a tensor -> tensor.dtype
2. To get shape from a tensor -> tensor.shape
3. To get device from a tensor -> tensor.device

</div>

In [29]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3773, 0.2665, 0.7643, 0.6767],
        [0.8691, 0.9996, 0.5988, 0.0346],
        [0.3978, 0.6106, 0.1158, 0.7039]])

In [30]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3773, 0.2665, 0.7643, 0.6767],
        [0.8691, 0.9996, 0.5988, 0.0346],
        [0.3978, 0.6106, 0.1158, 0.7039]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

<div style="font-size: 15px;">

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

</div>

#### Basic operations

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Mutiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

#### Matrix multiplication (dot product)

In [35]:
# Element wise multiplication
print(tensor, "*", tensor, end=" ")
print(f"= {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2.09 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 65.1 μs


tensor(14)

<div style="font-size: 15px;">

##### The main two rules for matrix multiplication:
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

**Note: `@`** in Python is the symbol for matrix multiplication.

</div>

In [39]:
# torch.rand(3, 2) @ torch.rand(3, 2) -> won't work because inner-dimension don't match
torch.rand(3, 2) @ torch.rand(2, 3)

tensor([[0.7232, 0.6476, 0.3409],
        [1.0949, 0.9505, 0.7149],
        [0.3856, 0.3444, 0.1876]])

### One of the most common errors in deep learning (shape errors)

In [40]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
# torch.mm() is an alias for torch.matmul()
torch.matmul(tensor_A, tensor_B) # (this will show error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

<div style="font-size: 15px;">

A **transpose** switches the dimensions of a given tensor
We can perform transposes in PyTorch using either:

1. `torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
2. `tensor.T` - where tensor is the desired tensor to transpose.

</div>

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

In [ ]:
import torch
from numpy import dtype
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T).type(torch.int32)
print(output)
print(f"\nOutput shape: {output.shape}")

## Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

<div style="font-size: 15px;">

**Note:** Some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

</div>

<div style="font-size: 15px;">

We can also do the same as above with torch methods:

</div>

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

## Positional min/max

<div style="font-size: 15px;">

We can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

</div>

In [ ]:
# Create a tensor
tensor = torch.arange(0, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

## Change tensor datatype

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

## Reshaping, stacking, squeezing and unsqueezing tensors

<div style="font-size: 15px;">

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

</div>

<div style="font-size: 15px;">

| Method | One-line description |
|---|---|
| `torch.reshape(input, shape)` | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| `Tensor.view(shape)` | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| `torch.stack(tensors, dim=0)` | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| `torch.squeeze(input)` | Squeezes `input` to remove all the dimensions with value `1`. |
| `torch.unsqueeze(input, dim)` | Returns `input` with a dimension value of `1` added at `dim`. |
| `torch.permute(input, dims)` | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

</div>


In [ ]:
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
# Add an extra dimension
x_reshaped_1 = x.reshape(1, 9)
x_reshaped_1, x_reshaped_1.shape, x_reshaped_1.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [ ]:
x_reshaped_2 = x.reshape(9, 1)
x_reshaped_2, x_reshaped_2.shape, x_reshaped_2.ndim

In [ ]:
x_reshaped_3 = x.reshape(3, 3)
x_reshaped_3, x_reshaped_3.shape, x_reshaped_3.ndim

In [ ]:
x = torch.arange(1., 11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [ ]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# Change the view
z = x.view(1, 10)
z, z.shape
# Changing the view of a tensor with torch.view() really only creates a new view of the same tensor. So changing the view changes the original tensor too

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[ 5.,  5.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.],
        [10., 10.]])

In [ ]:
# Remove extra dimension from x_reshaped
print(f"Previous tensor: {x_reshaped_1}")
print(f"Previous shape: {x_reshaped_1.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped_1.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a signle dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimension of a target tensor in a specific order
x_original = torch.rand(size=(244, 244, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


## Indexing (selecting data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Indexing most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# We can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 0, 0]

tensor([1])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

<div style="font-size: 15px;">

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

</div>

In [44]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [46]:
# Changing the value of array

array = array + 1
array, tensor # Doesnt change the values of the tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [59]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [61]:
# Changing the Tensor

tensor = tensor + 1
tensor, numpy_tensor # Doesnt change the values of the array

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)
<div style="font-size: 15px;">

In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

To reduce the randomness in neural networks and PyTorch comes the concept if **random seed**

Essentially what the random seed does ins "flavour" the randomness.

</div>

In [63]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5498, 0.0033, 0.5792, 0.0413],
        [0.5621, 0.1288, 0.5729, 0.3349],
        [0.7423, 0.7125, 0.8719, 0.2207]])
tensor([[0.5548, 0.1399, 0.7907, 0.8246],
        [0.2440, 0.4602, 0.4574, 0.5073],
        [0.7283, 0.9732, 0.0056, 0.9040]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [67]:
# random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs
<div style="font-size: 15px;">

`GPU = faster computation on numbers`

</div>

In [68]:
!nvidia-smi

Mon Jul 13 16:07:55 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 596.49                 Driver Version: 596.49         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   50C    P8              3W /  105W |    1473MiB /   6141MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [69]:
# Checking for GPU access

torch.cuda.is_available()

True

In [70]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [71]:
# Count number of devices

torch.cuda.device_count()

1

In [74]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [76]:
# Moving tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [78]:
# Moving tensors back to CPU

# tensor_on_gpu.numpy() -> will give error

In [81]:
# Setting tensor to CPU for NumPy operations

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [82]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')