In [91]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors
### Creating Tensors

In [92]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [93]:
scalar.ndim

0

In [94]:
# Get tensor back as Puython int
scalar.item()

7

In [95]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [96]:
vector.ndim

1

In [97]:
vector.shape

torch.Size([2])

In [98]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [99]:
MATRIX.ndim

2

In [100]:
MATRIX[0]

tensor([7, 8])

In [101]:
MATRIX[0][1]

tensor(8)

In [102]:
MATRIX.shape

torch.Size([2, 2])

In [103]:
# TENSOR
TENSOR = torch.tensor([[[ 4, 7, 2],
                        [ 9, 1, 5],
                        [ 3, 2, 8]],
                       [[3, 6, 2],
                        [9, 8, 4],
                        [4, 2, 6]],
                       [[8, 3, 3],
                        [9, 7, 5],
                        [8, 4, 7]]])

In [104]:
TENSOR

tensor([[[4, 7, 2],
         [9, 1, 5],
         [3, 2, 8]],

        [[3, 6, 2],
         [9, 8, 4],
         [4, 2, 6]],

        [[8, 3, 3],
         [9, 7, 5],
         [8, 4, 7]]])

In [105]:
TENSOR.ndim

3

In [106]:
TENSOR.shape

torch.Size([3, 3, 3])

In [107]:
TENSOR[0]

tensor([[4, 7, 2],
        [9, 1, 5],
        [3, 2, 8]])

### Random Tensors

In [108]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))

In [109]:
random_tensor, random_tensor.dtype

(tensor([[0.5415, 0.7244, 0.7272, 0.3735],
         [0.1902, 0.1176, 0.9152, 0.7823],
         [0.9082, 0.9478, 0.6308, 0.0712]]),
 torch.float32)

In [110]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zroes and Ones


In [111]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [112]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [113]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 1 to 10
zero_to_ten = torch.arange(start=1, end=11, step=1)
zero_to_ten

C:\Users\hossa\AppData\Local\Temp\ipykernel_14948\3427479621.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])